# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki


language: c
sudo: required

group: deprecated-2017Q4

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_bioc_deps
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github r-lib/testthat
  - ./travis-tool.sh install_github mskilab/gUtils
  - ./travis-tool.sh install_github mskilab/bamUtils

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change


r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
